prj_chuju/Controllers/BrandArticleController.cs
using prj_chuju.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace prj_chuju.Controllers
{
    public class BrandArticleController : Controller
    {
        static SqlConnectionStringBuilder myBuilder = new SqlConnectionStringBuilder()
        {
            DataSource = "chujudbserver.database.windows.net",
            InitialCatalog = "dbchuju",
            UserID = "chujuas",
            Password = "P@ssw0rd-chuju",
            AsynchronousProcessing = true,
        };
        static string conStr = myBuilder.ToString();

        // GET: BrandArticle
        public ActionResult Index()
        {
            List<class_articleOutline> list = new List<class_articleOutline>();

            SqlConnection con = new SqlConnection(conStr);
            SqlCommand cmd;
            SqlDataReader reader;

            con.Open();
            cmd = new SqlCommand("select * from articleOutline",con);
            reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                class_articleOutline ao = new class_articleOutline(reader);
                list.Add(ao);
            }
            con.Close();

            return View(list);
        }
    }
}

prj_chuju/Views/BrandArticle/Index.cshtml
@model List<prj_chuju.Models.class_articleOutline>

@{
    ViewBag.Title = "Index";
}

<link rel="stylesheet" href="~/style/newsStyle.css">

<main>
    <div class="container-fluid py-50 news">
        <h1 class="mt-3 mb-5 ml-5 font-weight-bold">所有文章</h1>

        <div class="w-75 d-flex flex-wrap mx-auto">

            @foreach (var item in Model)
            {
                <div class="col-6 news-item mb-30">
                    <figure>

                        @*這裡需要修正連結*@
                        <a href="@Url.Action("article","BrandArticle",new {id=item.id })"><img src="~/@item.pictureURL" alt="" class="w-75"></a>
                        <figcaption>

                            @*這個tag的部分要考慮要不要做*@
                            <a href="#2">
                                <i class="fas fa-tag"></i>
                                @*item.tag*@
                            </a>
                            <span>2022/1/18</span>
                        </figcaption>
                    </figure>

                    @*這裡需要修正連結*@
                    <a href="@Url.Action("article","BrandArticle",new {id=item.id })">
                        <h3>@item.title</h3>
                    </a>
                    <span>@item.articleSource</span>
                </div>
            }

        </div>

    </div>
</main>