prj_chuju/ViewModels/ArticleContentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace prj_chuju.ViewModels
{
    public class ArticleContentViewModel
    {
        
        public List<articleOutline> articleOutline { get; set; }
        public List<articleContent> articleContent { get; set; }
        public List<articleOutline> articleDetail { get; set; }
        
    }
}

prj_chuju/Controllers/BuyHouseFirstController.cs
using prj_chuju.Models;
using prj_chuju.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace prj_chuju.Controllers
{
    public class BuyHouseFirstController : Controller
    {
        // GET: BuyHouseFirst
        dbchujuEntities1 db = new dbchujuEntities1();
        public ActionResult Index()
        {
            
            var article = from p in db.articleOutline join x in db.articleClass on p.articleClass equals x.id where x.mainClass == "買房第一站" select p;

            return View(article);
        }

        public ActionResult ArticleContent(int id)
        {
            ArticleContentViewModel vm = new ArticleContentViewModel();
            vm.articleContent = db.articleContent.Where(t => t.articleID == id).ToList();
            int articleClass = db.articleOutline.Where(t => t.id == id).Select(p => p.articleClass).First();
            vm.articleOutline = db.articleOutline.Where(t => t.articleClass == articleClass).ToList();
            vm.articleDetail = db.articleOutline.Where(t => t.id == id).ToList();

            // 瀏覽歷史功能
            AccountInfoMemory userInfo = new AccountInfoHelper(Session, Request).Information;
            new factory_CollectAndViewed().visitArticle(userInfo.theid, (int)id);

            ViewBag.userID = userInfo.theid;
            ViewBag.articleID = id;

            return View(vm);
        }

        public ActionResult FirstStation()
        {
            var first = db.articleOutline.Join(db.articleClass, p => p.articleClass, x => x.id, (p, x) => p).Where(h => h.articleClass1.className == "買房第一站");

            return View(first);
        }

        public ActionResult MemberBenefits()
        {
            var member = from p in db.articleOutline where p.articleClass1.mainClass == "買房第一站" && p.articleClass1.className == "會員好康" select p;
            return View(member);
        }

        public ActionResult Design()
        {
            var design = from p in db.articleOutline where p.articleClass1.mainClass == "買房第一站" && p.articleClass1.className == "設計裝修" select p;
            return View(design);
        }

        public void collect()
        {
            int userID = Request["userID"] != null ? Convert.ToInt32(Request["userID"]) : -1;
            int articleID = Request["articleID"] != null ? Convert.ToInt32(Request["articleID"]) : -1;

            new factory_CollectAndViewed().collectArticle(userID, articleID);
        }
    }
}

prj_chuju/Views/BuyHouseFirst/AllArticle.cshtml
@model IEnumerable<project.articleOutline>

@{
    ViewBag.Title = "AllArticle";
}

<link rel="stylesheet" href="~/Content/allarticle.css" />
<nav>
    <div class="container-fluid bottom-nav">
        <div class="row top-nav align-items-center justify-content-between col-8">
            <div class="top-nav-left col-2">
            </div>
            <div class="top-nav-center row col-8">
                <a href="~/BuyHouseFirst/AllArticle">所有文章</a>
                <a href="~/BuyHouseFirst/FirstStation">買房第一站</a>
                <a href="~/BuyHouseFirst/MemberBenefits">會員好康</a>
                <a href="~/BuyHouseFirst/Design">設計裝修</a>
            </div>
            <div class="top-nav-right row align-items-center justify-content-center col-2">
            </div>
        </div>
    </div>
</nav>
<main>
    <div class="container-fluid py-50 news">
        <h1 class="mt-3 mb-5 ml-5 font-weight-bold">所有文章</h1>
        @foreach (var item in Model)
        {
            <div class="d-flex w-75 flex-wrap mx-auto border-b">
                <div class="col-md-6 news-item my-3">
                    <a href="~/BuyHouseFirst/ArticleContent/@item.id"><img src="~/@item.pictureURL" alt="" class="img-fluid"></a>
                </div>
                <div class="col-md-6 news-item my-3">
                    <div class="title-box h-50">
                        <div class="d-flex justify-content-between">
                            <a href="~/BuyHouseFirst/ArticleContent/@item.id">
                                <i class="fas fa-tag"></i>
                                @item.articleClass1.className
                            </a>
                            <span>@Html.DisplayFor(ModelItem => item.publishDate)</span>
                        </div>

                        <a href="#1"><h3>@item.title</h3></a>
                    </div>
                    <div class="tag-box h-50 d-flex align-items-end">
                        @foreach (var tag in item.articleTagList)
                        {
                            <span class="tag">@tag.tagName</span>
                        }
                    </div>

                </div>
            </div>

        }

    </div>
</main>

prj_chuju/Views/BuyHouseFirst/ArticleContent.cshtml
@model prj_chuju.ViewModels.ArticleContentViewModel
@{
    ViewBag.Title = "ArticleContent";
}
<link rel="stylesheet" href="~/style/articlecontent.css" />
<nav>
    <div class="container-fluid bottom-nav">
        <div class="bottom-nav-center py-10">
            <a href="~/BuyHouseFirst/Index">所有文章</a>
            <a href="~/BuyHouseFirst/FirstStation">買房第一站</a>
            <a href="~/BuyHouseFirst/MemberBenefits">會員好康</a>
            <a href="~/BuyHouseFirst/Design">設計裝修</a>
        </div>
    </div>
</nav>
<main>
    <div class="container-fluid py-50">
        <div class="d詳細資訊">
            @foreach (var item in Model.articleDetail)
            {
                <p class="text font-weight-bolder">@item.articleClass1.className</p>
                <p class="text">刊出日期 @Html.DisplayFor(modelitem => item.publishDate)</p>
                <p class="text">文字 / 林建評</p>
                <button class="btn-like">收藏</button>
                <div class="tag d-flex justify-content-start flex-wrap">
                    @foreach (var tag in item.articleTagList)
                    {
                        <div>#@tag.tagName</div>
                    }
                </div>
            }
        </div>
        <div class="btn-tool">
            <a href=""><img src="images/P/text.png" alt=""></a>
            <a href=""><img src="images/P/printer.png" alt=""></a>
            <a href=""><img src="images/P/facebook.png" alt=""></a>
            <a href=""><img src="images/P/twitter.png" alt=""></a>
            <a href=""><img src="images/P/line.png" alt=""></a>
        </div>
        <div class="row article">
            <div class="col-6 m-auto">
                <div class="title">
                    <h1></h1>
                </div>
                <div class="title-image">
                    <img src="" alt="">
                    <div class="text">
                        <p></p>
                    </div>
                </div>
                <div class="contents">
                    @foreach (var item in Model.articleContent)
                    {
                        switch (item.contentType)
                        {
                            case "title":
                                <div class="title">
                                    <h2>@item.textContent</h2>
                                </div>
                                break;
                            case "picture":
                                <div class="image">
                                    <img src="~/images/@item.articlePicture.pictureURL" alt="">
                                </div>
                                break;
                            case "text":
                                <div class="text">
                                    <p class="">@item.textContent</p>
                                </div>
                                break;
                        }
                    }
                </div>
                <p>相關文章</p>
                <div class="row other-news">
                    @foreach (var item in Model.articleOutline)
                    {
                        <div class="col-3">
                            <a href="~/MarketNews/ArticleContent/@item.id">
                                <img src="~/@item.pictureURL" alt="">
                                <p class="tag">@item.articleClass1.className</p>
                                <p>@item.title</p>
                            </a>
                            <p class="date">2022/01/19</p>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</main>
<script>
    const userID = @ViewBag.userID;
    const articleID = @ViewBag.articleID;
    $(function () {
        $(".btn-like").click(function () {
            if (userID < 0) {
                alert("請先登入！");
            } else {
                $.ajax({
                    method: 'post',
                    url: '@Url.Action("collect","BuyHouseFirst")',
                    data: {
                        userID,
                        articleID,
                    },
                    success: function () {
                        $(".btn-like").text("已收藏").attr("disabled", true);
                    }
                });
            }
        });
    });
</script>

prj_chuju/Views/BuyHouseFirst/Design.cshtml
@model IEnumerable<prj_chuju.articleOutline>
@{
    ViewBag.Title = "Design";
}
<link rel="stylesheet" href="~/style/allarticle.css" />
<nav>
    <div class="container-fluid bottom-nav">
        <div class="bottom-nav-center py-10">
            <a href="~/BuyHouseFirst/Index">所有文章</a>
            <a href="~/BuyHouseFirst/FirstStation">買房第一站</a>
            <a href="~/BuyHouseFirst/MemberBenefits">會員好康</a>
            <a href="~/BuyHouseFirst/Design">設計裝修</a>
        </div>
    </div>
</nav>
<main>
    <div class="container-fluid py-50 news">
        <h1 class="mt-3 mb-5 ml-5 font-weight-bold">設計裝修</h1>
        @foreach (var item in Model)
        {
            <div class="d-flex w-75 flex-wrap mx-auto border-b">
                <div class="col-md-6 news-item my-3">
                    <a href="~/BuyHouseFirst/ArticleContent/@item.id"><img src="~/@item.pictureURL" alt="" class="img-fluid"></a>
                </div>
                <div class="col-md-6 news-item my-3">
                    <div class="title-box h-50">
                        <div class="d-flex justify-content-between">
                            <a href="~/BuyHouseFirst/ArticleContent/@item.id">
                                <i class="fas fa-tag"></i>
                                @item.articleClass1.className
                            </a>
                            <span>@Html.DisplayFor(ModelItem => item.publishDate)</span>
                        </div>

                        <a href="~/BuyHouseFirst/ArticleContent/@item.id"><h3>@item.title</h3></a>
                        <div>
                            @item.intro
                        </div>
                    </div>
                    <div class="tag-box h-50 d-flex align-items-end">
                        <div>
                            @foreach (var tag in item.articleTagList)
                            {
                                <span class="tag">@tag.tagName</span>
                            }
                        </div>
                    </div>

                </div>
            </div>

        }

    </div>
</main>

prj_chuju/Views/BuyHouseFirst/FirstStation.cshtml
@model IEnumerable<prj_chuju.articleOutline>
@{
    ViewBag.Title = "FirstStation";
}

<link rel="stylesheet" href="~/style/allarticle.css" />
<nav>
    <div class="container-fluid bottom-nav">
        <div class="bottom-nav-center py-10">
            <a href="~/BuyHouseFirst/Index">所有文章</a>
            <a href="~/BuyHouseFirst/FirstStation">買房第一站</a>
            <a href="~/BuyHouseFirst/MemberBenefits">會員好康</a>
            <a href="~/BuyHouseFirst/Design">設計裝修</a>
        </div>
    </div>
</nav>
<main>
    <div class="container-fluid py-50 news">
        <h1 class="mt-3 mb-5 ml-5 font-weight-bold">所有文章</h1>
        @foreach (var item in Model)
        {
            <div class="d-flex w-75 flex-wrap mx-auto border-b">
                <div class="col-md-6 news-item my-3">
                    <a href="~/BuyHouseFirst/ArticleContent/@item.id"><img src="~/@item.pictureURL" alt="" class="img-fluid"></a>
                </div>
                <div class="col-md-6 news-item my-3">
                    <div class="title-box h-50">
                        <div class="d-flex justify-content-between">
                            <a href="~/BuyHouseFirst/ArticleContent/@item.id">
                                <i class="fas fa-tag"></i>
                                @item.articleClass1.className
                            </a>
                            <span>@Html.DisplayFor(ModelItem => item.publishDate)</span>
                        </div>

                        <a href="~/BuyHouseFirst/ArticleContent/@item.id"><h3>@item.title</h3></a>
                        <div>
                            @item.intro
                        </div>
                    </div>
                    <div class="tag-box h-50 d-flex align-items-end">
                        <div>
                            @foreach (var tag in item.articleTagList)
                            {
                                <span class="tag">@tag.tagName</span>
                            }
                        </div>
                    </div>

                </div>
            </div>

        }

    </div>
</main>

prj_chuju/Views/BuyHouseFirst/Index.cshtml
@model IEnumerable<prj_chuju.articleOutline>

@{
    ViewBag.Title = "Index";
}

<link rel="stylesheet" href="~/style/allarticle.css" />
<nav>
    <div class="container-fluid bottom-nav">
        <div class="bottom-nav-center py-10">
            <a href="~/BuyHouseFirst/Index">所有文章</a>
            <a href="~/BuyHouseFirst/FirstStation">買房第一站</a>
            <a href="~/BuyHouseFirst/MemberBenefits">會員好康</a>
            <a href="~/BuyHouseFirst/Design">設計裝修</a>
        </div>
    </div>
</nav>
<main>
    <div class="container-fluid py-50 news">
        <h1 class="mt-3 mb-5 ml-5 font-weight-bold">所有文章</h1>
        @foreach (var item in Model)
        {
            <div class="d-flex w-75 flex-wrap mx-auto border-b">
                <div class="col-md-6 news-item my-3">
                    <a href="~/BuyHouseFirst/ArticleContent/@item.id"><img src="~/@item.pictureURL" alt="" class="img-fluid"></a>
                </div>
                <div class="col-md-6 news-item my-3">
                    <div class="title-box h-50">
                        <div class="d-flex justify-content-between">
                            <a href="~/BuyHouseFirst/ArticleContent/@item.id">
                                <i class="fas fa-tag"></i>
                                @item.articleClass1.className
                            </a>
                            <span>@Html.DisplayFor(ModelItem => item.publishDate)</span>
                        </div>

                        <a href="~/BuyHouseFirst/ArticleContent/@item.id"><h3>@item.title</h3></a>
                        <div>
                            @item.intro
                        </div>
                    </div>
                    <div class="tag-box h-50 d-flex align-items-end">
                        <div>
                            @foreach (var tag in item.articleTagList)
                            {
                                <span class="tag">@tag.tagName</span>
                            }
                        </div>
                    </div>

                </div>
            </div>

        }

    </div>
</main>

prj_chuju/Views/BuyHouseFirst/MemberBenefits.cshtml
@model IEnumerable<prj_chuju.articleOutline>
@{
    ViewBag.Title = "MemberBenefits";
}
<link rel="stylesheet" href="~/style/allarticle.css" />
<nav>
    <div class="container-fluid bottom-nav">
        <div class="bottom-nav-center py-10">
            <a href="~/BuyHouseFirst/Index">所有文章</a>
            <a href="~/BuyHouseFirst/FirstStation">買房第一站</a>
            <a href="~/BuyHouseFirst/MemberBenefits">會員好康</a>
            <a href="~/BuyHouseFirst/Design">設計裝修</a>
        </div>
    </div>
</nav>
<main>
    <div class="container-fluid py-50 news">
        <h1 class="mt-3 mb-5 ml-5 font-weight-bold">會員好康</h1>
        @foreach (var item in Model)
        {
            <div class="d-flex w-75 flex-wrap mx-auto border-b">
                <div class="col-md-6 news-item my-3">
                    <a href="~/BuyHouseFirst/ArticleContent/@item.id"><img src="~/@item.pictureURL" alt="" class="img-fluid"></a>
                </div>
                <div class="col-md-6 news-item my-3">
                    <div class="title-box h-50">
                        <div class="d-flex justify-content-between">
                            <a href="~/BuyHouseFirst/ArticleContent/@item.id">
                                <i class="fas fa-tag"></i>
                                @item.articleClass1.className
                            </a>
                            <span>@Html.DisplayFor(ModelItem => item.publishDate)</span>
                        </div>

                        <a href="~/BuyHouseFirst/ArticleContent/@item.id"><h3>@item.title</h3></a>
                        <div>
                            @item.intro
                        </div>
                    </div>
                    <div class="tag-box h-50 d-flex align-items-end">
                        <div>
                            @foreach (var tag in item.articleTagList)
                            {
                                <span class="tag">@tag.tagName</span>
                            }
                        </div>
                    </div>
                </div>
            </div>

        }

    </div>
</main>